export const FIELDS = Object.freeze({
  EMAIL: 'EMAIL',
  NAME: 'NAME',
  SURNAME: 'SURNAME',
  PASSWORD: 'PASSWORD',
  CONFIRM_PASSWORD: 'CONFIRM_PASSWORD'
});

export const REGISTER_STATUSES = Object.freeze({
  WAITING_USER: 'WAITING_USER',
  WAITING_API: 'WAITING_API',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  ERROR: 'ERROR',
  REGISTERED: 'REGISTERED'
});
